### ISSUE TITLE
Ошибка с контекстом при билде проекта (forbidden path outside the build context: ../poetry.lock ())

### ISSUE THREAD

**Issue by simonoffcc** [MassonNN/masson-aiogram-template#18]
При билде проекта через sudo make project-start вот такая ошибка: 
```
ERROR: Service 'bot' failed to build: COPY failed: forbidden path outside the build context: ../poetry.lock ()
make: *** [Makefile:61: project-start] Error 1
```

В ней очевидно и понятно что не так, при этом прогуглив, нашёл такое решение: https://stackoverflow.com/questions/69615253/copy-failed-forbidden-path-outside-the-build-context-docker-compose. 
Однако сам сделал немного по-другому, заменив в Dockerfile с 
```yml
WORKDIR /app
COPY ../poetry.lock pyproject.toml ./
```
на
```yml
WORKDIR /app
COPY poetry.lock pyproject.toml ./
```
И вроде как всё заработало. Я думаю, проблема не только у меня, либо я что-то не так делаю. Поправьте если так.

Предположили, что проблема может быть с контекстом. Вот соответствующие выводы:
![изображение](https://github.com/MassonNN/masson-aiogram-template/assets/45663683/44ba00c1-fdbb-4413-b6dc-600e6f537f02)
![изображение](https://github.com/MassonNN/masson-aiogram-template/assets/45663683/ed1956be-1149-4763-91cf-8ce4586ade9b)

Полный Dockerfile  (не изменён, такой же как в шаблоне):
```Dockerfile
FROM python:3.10-slim as python-base

ENV POETRY_VERSION=1.5.1 \
    POETRY_HOME=/opt/poetry \
    POETRY_VENV=/opt/poetry-venv \
    POETRY_CACHE_DIR=/opt/.cache
    
FROM python-base as poetry-base

RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

FROM python-base as app

COPY --from=poetry-base ${POETRY_VENV} ${POETRY_VENV}
ENV PATH="${PATH}:${POETRY_VENV}/bin"

WORKDIR /app
COPY ../poetry.lock pyproject.toml ./

RUN poetry check && \
    poetry install --no-interaction --no-cache --no-root

COPY .. .
CMD ["poetry", "run", "python", "-m", "src.bot"]
```

Полный docker-compose.yml (не изменён, такой же как в шаблоне):
```yml
version: '3.7'
services:
  redis:
    build:
      context: buildfiles
      dockerfile: redis.dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "6378:6378"
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata:
```
